// <auto-generated />
using IGraficaIES.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IGraficaGym.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260223201620_final")]
    partial class final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IGraficaIES.MonitorGymExtendido", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ECivil")
                        .HasColumnType("bigint");

                    b.Property<int>("Estatura")
                        .HasColumnType("int");

                    b.Property<string>("MonitorGymPublicoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonitorGymPublicoId")
                        .IsUnique();

                    b.ToTable("MonitoresExtendidos");
                });

            modelBuilder.Entity("_2HerenciaSimpleIES.MonitorGymPublico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnyoIngresoCuerpo")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DestinoDefinitivo")
                        .HasColumnType("bit");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Especializacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TipoMedico")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoMonitor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MonitoresFuncionarios");
                });

            modelBuilder.Entity("IGraficaIES.MonitorGymExtendido", b =>
                {
                    b.HasOne("_2HerenciaSimpleIES.MonitorGymPublico", null)
                        .WithOne("MonitorGymExtendido")
                        .HasForeignKey("IGraficaIES.MonitorGymExtendido", "MonitorGymPublicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2HerenciaSimpleIES.MonitorGymPublico", b =>
                {
                    b.Navigation("MonitorGymExtendido")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
